events {
    worker_connections 1024;
}

http {
    resolver 127.0.0.11 valid=10s;

    upstream backend_pool {
        server backend-1:8080;
        server backend-2:8080;
    }

    geo $allowed {
        default                                      0;
        127.0.0.1                                    1;
        172.16.0.0/12                                1;
        192.168.0.0/16                               1;
        10.0.0.0/8                                   1;
        10.147.18.84                                 1;
        109.166.137.158                              1;
        146.190.3.114                                1;
    }

    server {
        listen 8080;
        server_name mygamelist.local;

        location /api/steam/ {
            set $frontend http://frontend:3000;
            proxy_pass         $frontend;
            proxy_set_header   Host              $host;
            proxy_set_header   X-Real-IP         $remote_addr;
            proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Proto $scheme;
        }

        location /api/ {
            proxy_pass         http://backend_pool;
            proxy_set_header   Host              $host;
            proxy_set_header   X-Real-IP         $remote_addr;
            proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Proto $scheme;
        }

        location /logs/ {
            if ($allowed = 0) {
                return 403;
            }

            set $dozzle http://dozzle:8080;
            proxy_pass         $dozzle;
            proxy_set_header   Host              $host;
            proxy_set_header   X-Real-IP         $remote_addr;

            proxy_http_version 1.1;
            proxy_set_header   Upgrade    $http_upgrade;
            proxy_set_header   Connection "upgrade";
        }

        location / {
            set $frontend http://frontend:3000;
            proxy_pass         $frontend;
            proxy_set_header   Host              $host;
            proxy_set_header   X-Real-IP         $remote_addr;
            proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        }
    }

    server {
        listen 8443 ssl;
        server_name mygamelist.local;

        ssl_certificate     /etc/nginx/ssl/cert.pem;
        ssl_certificate_key /etc/nginx/ssl/key.pem;

        location /api/steam/ {
            set $frontend http://frontend:3000;
            proxy_pass         $frontend;
            proxy_set_header   Host              $host;
            proxy_set_header   X-Real-IP         $remote_addr;
            proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Proto $scheme;
        }

        location /api/ {
            proxy_pass         http://backend_pool;
            proxy_set_header   Host              $host;
            proxy_set_header   X-Real-IP         $remote_addr;
            proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Proto $scheme;
        }

        location /logs/ {
            if ($allowed = 0) {
                return 403;
            }

            set $dozzle http://dozzle:8080;
            proxy_pass         $dozzle;
            proxy_set_header   Host              $host;
            proxy_set_header   X-Real-IP         $remote_addr;
            proxy_http_version 1.1;
            proxy_set_header   Upgrade    $http_upgrade;
            proxy_set_header   Connection "upgrade";
        }

        location / {
            set $frontend http://frontend:3000;
            proxy_pass         $frontend;
            proxy_set_header   Host              $host;
            proxy_set_header   X-Real-IP         $remote_addr;
            proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        }
    }
}
